version: '3.8'

services:
  learn_mmseg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mmseg1127_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
