version: '3.8'

services:
  learn_mmseg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mmseg1127_container
    volumes:
      - /workspace/visual_ws/Seg_ws:/mmseg
    command: bash
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
